name: 0303-build-tomcat
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out 0303-tomcat-users.xml
      uses: actions/checkout@v3

    - name: List project files and java version
      run: |
          ls -ltr
          java -version

    - name: Check out Apache Tomcat
      uses: actions/checkout@v3
      with:
        repository: apache/tomcat # Repository name with owner
        ref: main               # The branch, tag or SHA to checkout
        path: ./tomcat            # Relative path under $GITHUB_WORKSPACE

    - name: Setup Java 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11.0.1'     # The JDK version to make available on the path
        java-package: jdk         # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64         # (x64 or x86) - defaults to x64
        
    - name: List project files and java version
      run: |
          ls -ltr
          java -version

    - name: Copy 0303-tomcat-users.xml into Tomcat configuration directory
      run: cp -v 0303-tomcat-users.xml ./tomcat/conf/tomcat-users.xml

    - name: Compile Tomcat
      run: |
        cd ./tomcat
        ant
