name: first
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
jobs:
  jobs1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3
      - name: Step two
        run: env | sort
  jobs2:
    name: Second job
    needs: jobs1
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v3      
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"
  
