# Push trigger | four jobs | print the date
# Job 1 - ubuntu-latest
# Job 2 - windows-latest
# Job 3 - macos-latest
# Job 4 - any runner ! depends on jobs 1, 2, and 3
name: ch02-challenge
on: push
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: "date +%F"
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3      
      - run: Get-Date
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3      
      - run: "date +%F"
  depends:
    needs: [ubuntu, windows, macos]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3      
    - run: "date +%F"
  
